/* File: world2vox_fortran.cpython-310-x86_64-linux-gnu.somodule.c
 * This file is auto-generated with f2py (version:2.0.1).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Aug 15 17:07:01 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *world2vox_fortran.cpython-310-x86_64-linux-gnu.so_error;
static PyObject *world2vox_fortran.cpython-310-x86_64-linux-gnu.so_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
/*need_cfuncs*/

/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(world2vox_f,WORLD2VOX_F)(int*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** world2vox_f ********************************/
static char doc_f2py_rout_world2vox_fortran.cpython-310-x86_64-linux-gnu.so_world2vox_f[] = "\
list = world2vox_f(world)\n\nWrapper for ``world2vox_f``.\
\n\nParameters\n----------\n"
"world : input rank-3 array('d') with bounds (10,10,10)\n"
"\nReturns\n-------\n"
"list : rank-1 array('i') with bounds (1000)";
/* extern void F_FUNC_US(world2vox_f,WORLD2VOX_F)(int*,double*); */
static PyObject *f2py_rout_world2vox_fortran.cpython-310-x86_64-linux-gnu.so_world2vox_f(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int *list = NULL;
    npy_intp list_Dims[1] = {-1};
    const int list_Rank = 1;
    PyArrayObject *capi_list_as_array = NULL;
    int capi_list_intent = 0;
    double *world = NULL;
    npy_intp world_Dims[3] = {-1, -1, -1};
    const int world_Rank = 3;
    PyArrayObject *capi_world_as_array = NULL;
    int capi_world_intent = 0;
    PyObject *world_capi = Py_None;
    static char *capi_kwlist[] = {"world",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:world2vox_fortran.cpython-310-x86_64-linux-gnu.so.world2vox_f",\
        capi_kwlist,&world_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable world */
    world_Dims[0]=10,world_Dims[1]=10,world_Dims[2]=10;
    capi_world_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "world2vox_fortran.cpython-310-x86_64-linux-gnu.so.world2vox_fortran.cpython-310-x86_64-linux-gnu.so.world2vox_f: failed to create array from the 1st argument `world`";
    capi_world_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,world_Dims,world_Rank,  capi_world_intent,world_capi,capi_errmess);
    if (capi_world_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = world2vox_fortran.cpython-310-x86_64-linux-gnu.so_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        world = (double *)(PyArray_DATA(capi_world_as_array));

    /* Processing variable list */
    list_Dims[0]=1000;
    capi_list_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "world2vox_fortran.cpython-310-x86_64-linux-gnu.so.world2vox_fortran.cpython-310-x86_64-linux-gnu.so.world2vox_f: failed to create array from the hidden `list`";
    capi_list_as_array = ndarray_from_pyobj(  NPY_INT,1,list_Dims,list_Rank,  capi_list_intent,Py_None,capi_errmess);
    if (capi_list_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = world2vox_fortran.cpython-310-x86_64-linux-gnu.so_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        list = (int *)(PyArray_DATA(capi_list_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(list,world);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_list_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_list_as_array == NULL) ... else of list */
    /* End of cleaning variable list */
    if((PyObject *)capi_world_as_array!=world_capi) {
        Py_XDECREF(capi_world_as_array); }
    }  /* if (capi_world_as_array == NULL) ... else of world */
    /* End of cleaning variable world */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of world2vox_f *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"world2vox_f",-1,{{-1}},0,0,(char *)  F_FUNC_US(world2vox_f,WORLD2VOX_F),  (f2py_init_func)f2py_rout_world2vox_fortran.cpython-310-x86_64-linux-gnu.so_world2vox_f,doc_f2py_rout_world2vox_fortran.cpython-310-x86_64-linux-gnu.so_world2vox_f},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "world2vox_fortran.cpython-310-x86_64-linux-gnu.so",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_world2vox_fortran.cpython-310-x86_64-linux-gnu.so(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = world2vox_fortran.cpython-310-x86_64-linux-gnu.so_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module world2vox_fortran.cpython-310-x86_64-linux-gnu.so (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.0.1");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'world2vox_fortran.cpython-310-x86_64-linux-gnu.so' is auto-generated with f2py (version:2.0.1).\nFunctions:\n"
"    list = world2vox_f(world)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.0.1");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    world2vox_fortran.cpython-310-x86_64-linux-gnu.so_error = PyErr_NewException ("world2vox_fortran.cpython-310-x86_64-linux-gnu.so.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_world2vox_fortran.cpython-310-x86_64-linux-gnu.so_error", world2vox_fortran.cpython-310-x86_64-linux-gnu.so_error);
    Py_DECREF(world2vox_fortran.cpython-310-x86_64-linux-gnu.so_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"world2vox_fortran.cpython-310-x86_64-linux-gnu.so");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
