/* File: g_gentorusmodule.c
 * This file is auto-generated with f2py (version:2.0.1).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Aug 15 20:28:13 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *g_gentorus_error;
static PyObject *g_gentorus_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = g_gentorus_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = g_gentorus_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(gen_torus,GEN_TORUS)(double*,int*,double*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* gen_torus *********************************/
static char doc_f2py_rout_g_gentorus_gen_torus[] = "\
world = gen_torus(n,thickness,xpos,ypos,zpos)\n\nWrapper for ``gen_torus``.\
\n\nParameters\n----------\n"
"n : input int\n"
"thickness : input float\n"
"xpos : input rank-1 array('d') with bounds (25)\n"
"ypos : input rank-1 array('d') with bounds (25)\n"
"zpos : input rank-1 array('d') with bounds (25)\n"
"\nReturns\n-------\n"
"world : rank-3 array('d') with bounds (10,10,10)";
/* extern void F_FUNC_US(gen_torus,GEN_TORUS)(double*,int*,double*,double*,double*,double*); */
static PyObject *f2py_rout_g_gentorus_gen_torus(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *world = NULL;
    npy_intp world_Dims[3] = {-1, -1, -1};
    const int world_Rank = 3;
    PyArrayObject *capi_world_as_array = NULL;
    int capi_world_intent = 0;
    int n = 0;
    PyObject *n_capi = Py_None;
    double thickness = 0;
    PyObject *thickness_capi = Py_None;
    double *xpos = NULL;
    npy_intp xpos_Dims[1] = {-1};
    const int xpos_Rank = 1;
    PyArrayObject *capi_xpos_as_array = NULL;
    int capi_xpos_intent = 0;
    PyObject *xpos_capi = Py_None;
    double *ypos = NULL;
    npy_intp ypos_Dims[1] = {-1};
    const int ypos_Rank = 1;
    PyArrayObject *capi_ypos_as_array = NULL;
    int capi_ypos_intent = 0;
    PyObject *ypos_capi = Py_None;
    double *zpos = NULL;
    npy_intp zpos_Dims[1] = {-1};
    const int zpos_Rank = 1;
    PyArrayObject *capi_zpos_as_array = NULL;
    int capi_zpos_intent = 0;
    PyObject *zpos_capi = Py_None;
    static char *capi_kwlist[] = {"n","thickness","xpos","ypos","zpos",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|:g_gentorus.gen_torus",\
        capi_kwlist,&n_capi,&thickness_capi,&xpos_capi,&ypos_capi,&zpos_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable thickness */
        f2py_success = double_from_pyobj(&thickness,thickness_capi,"g_gentorus.gen_torus() 2nd argument (thickness) can't be converted to double");
    if (f2py_success) {
    /* Processing variable xpos */
    xpos_Dims[0]=25;
    capi_xpos_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "g_gentorus.g_gentorus.gen_torus: failed to create array from the 3rd argument `xpos`";
    capi_xpos_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,xpos_Dims,xpos_Rank,  capi_xpos_intent,xpos_capi,capi_errmess);
    if (capi_xpos_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_gentorus_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        xpos = (double *)(PyArray_DATA(capi_xpos_as_array));

    /* Processing variable ypos */
    ypos_Dims[0]=25;
    capi_ypos_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "g_gentorus.g_gentorus.gen_torus: failed to create array from the 4th argument `ypos`";
    capi_ypos_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ypos_Dims,ypos_Rank,  capi_ypos_intent,ypos_capi,capi_errmess);
    if (capi_ypos_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_gentorus_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ypos = (double *)(PyArray_DATA(capi_ypos_as_array));

    /* Processing variable zpos */
    zpos_Dims[0]=25;
    capi_zpos_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "g_gentorus.g_gentorus.gen_torus: failed to create array from the 5th argument `zpos`";
    capi_zpos_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,zpos_Dims,zpos_Rank,  capi_zpos_intent,zpos_capi,capi_errmess);
    if (capi_zpos_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_gentorus_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        zpos = (double *)(PyArray_DATA(capi_zpos_as_array));

    /* Processing variable world */
    world_Dims[0]=10,world_Dims[1]=10,world_Dims[2]=10;
    capi_world_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "g_gentorus.g_gentorus.gen_torus: failed to create array from the hidden `world`";
    capi_world_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,world_Dims,world_Rank,  capi_world_intent,Py_None,capi_errmess);
    if (capi_world_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_gentorus_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        world = (double *)(PyArray_DATA(capi_world_as_array));

    /* Processing variable n */
        f2py_success = int_from_pyobj(&n,n_capi,"g_gentorus.gen_torus() 1st argument (n) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(world,&n,&thickness,xpos,ypos,zpos);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_world_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    }  /* if (capi_world_as_array == NULL) ... else of world */
    /* End of cleaning variable world */
    if((PyObject *)capi_zpos_as_array!=zpos_capi) {
        Py_XDECREF(capi_zpos_as_array); }
    }  /* if (capi_zpos_as_array == NULL) ... else of zpos */
    /* End of cleaning variable zpos */
    if((PyObject *)capi_ypos_as_array!=ypos_capi) {
        Py_XDECREF(capi_ypos_as_array); }
    }  /* if (capi_ypos_as_array == NULL) ... else of ypos */
    /* End of cleaning variable ypos */
    if((PyObject *)capi_xpos_as_array!=xpos_capi) {
        Py_XDECREF(capi_xpos_as_array); }
    }  /* if (capi_xpos_as_array == NULL) ... else of xpos */
    /* End of cleaning variable xpos */
    } /*if (f2py_success) of thickness*/
    /* End of cleaning variable thickness */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of gen_torus ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"gen_torus",-1,{{-1}},0,0,(char *)  F_FUNC_US(gen_torus,GEN_TORUS),  (f2py_init_func)f2py_rout_g_gentorus_gen_torus,doc_f2py_rout_g_gentorus_gen_torus},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "g_gentorus",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_g_gentorus(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = g_gentorus_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module g_gentorus (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.0.1");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'g_gentorus' is auto-generated with f2py (version:2.0.1).\nFunctions:\n"
"    world = gen_torus(n,thickness,xpos,ypos,zpos)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.0.1");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    g_gentorus_error = PyErr_NewException ("g_gentorus.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_g_gentorus_error", g_gentorus_error);
    Py_DECREF(g_gentorus_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"g_gentorus");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
