/* File: g_lightsaber_fmodule.c
 * This file is auto-generated with f2py (version:2.0.1).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Aug 15 20:18:56 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *g_lightsaber_f_error;
static PyObject *g_lightsaber_f_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
/*need_cfuncs*/

/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(gen_lightsaber,GEN_LIGHTSABER)(double*,int*,int*);
extern void F_WRAPPEDFUNC(cross,CROSS)(int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* gen_lightsaber *******************************/
static char doc_f2py_rout_g_lightsaber_f_gen_lightsaber[] = "\
world = gen_lightsaber(pout,point)\n\nWrapper for ``gen_lightsaber``.\
\n\nParameters\n----------\n"
"pout : input rank-1 array('i') with bounds (3)\n"
"point : input rank-1 array('i') with bounds (3)\n"
"\nReturns\n-------\n"
"world : rank-3 array('d') with bounds (10,10,10)";
/* extern void F_FUNC_US(gen_lightsaber,GEN_LIGHTSABER)(double*,int*,int*); */
static PyObject *f2py_rout_g_lightsaber_f_gen_lightsaber(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *world = NULL;
    npy_intp world_Dims[3] = {-1, -1, -1};
    const int world_Rank = 3;
    PyArrayObject *capi_world_as_array = NULL;
    int capi_world_intent = 0;
    int *pout = NULL;
    npy_intp pout_Dims[1] = {-1};
    const int pout_Rank = 1;
    PyArrayObject *capi_pout_as_array = NULL;
    int capi_pout_intent = 0;
    PyObject *pout_capi = Py_None;
    int *point = NULL;
    npy_intp point_Dims[1] = {-1};
    const int point_Rank = 1;
    PyArrayObject *capi_point_as_array = NULL;
    int capi_point_intent = 0;
    PyObject *point_capi = Py_None;
    static char *capi_kwlist[] = {"pout","point",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:g_lightsaber_f.gen_lightsaber",\
        capi_kwlist,&pout_capi,&point_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable pout */
    pout_Dims[0]=3;
    capi_pout_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "g_lightsaber_f.g_lightsaber_f.gen_lightsaber: failed to create array from the 1st argument `pout`";
    capi_pout_as_array = ndarray_from_pyobj(  NPY_INT,1,pout_Dims,pout_Rank,  capi_pout_intent,pout_capi,capi_errmess);
    if (capi_pout_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_lightsaber_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        pout = (int *)(PyArray_DATA(capi_pout_as_array));

    /* Processing variable point */
    point_Dims[0]=3;
    capi_point_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "g_lightsaber_f.g_lightsaber_f.gen_lightsaber: failed to create array from the 2nd argument `point`";
    capi_point_as_array = ndarray_from_pyobj(  NPY_INT,1,point_Dims,point_Rank,  capi_point_intent,point_capi,capi_errmess);
    if (capi_point_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_lightsaber_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        point = (int *)(PyArray_DATA(capi_point_as_array));

    /* Processing variable world */
    world_Dims[0]=10,world_Dims[1]=10,world_Dims[2]=10;
    capi_world_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "g_lightsaber_f.g_lightsaber_f.gen_lightsaber: failed to create array from the hidden `world`";
    capi_world_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,world_Dims,world_Rank,  capi_world_intent,Py_None,capi_errmess);
    if (capi_world_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_lightsaber_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        world = (double *)(PyArray_DATA(capi_world_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(world,pout,point);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_world_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_world_as_array == NULL) ... else of world */
    /* End of cleaning variable world */
    if((PyObject *)capi_point_as_array!=point_capi) {
        Py_XDECREF(capi_point_as_array); }
    }  /* if (capi_point_as_array == NULL) ... else of point */
    /* End of cleaning variable point */
    if((PyObject *)capi_pout_as_array!=pout_capi) {
        Py_XDECREF(capi_pout_as_array); }
    }  /* if (capi_pout_as_array == NULL) ... else of pout */
    /* End of cleaning variable pout */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of gen_lightsaber ***************************/

/*********************************** cross ***********************************/
static char doc_f2py_rout_g_lightsaber_f_cross[] = "\
cross = cross(a,b)\n\nWrapper for ``cross``.\
\n\nParameters\n----------\n"
"a : input rank-1 array('i') with bounds (3)\n"
"b : input rank-1 array('i') with bounds (3)\n"
"\nReturns\n-------\n"
"cross : rank-1 array('i') with bounds (3)";
/* extern void F_WRAPPEDFUNC(cross,CROSS)(int*,int*,int*); */
static PyObject *f2py_rout_g_lightsaber_f_cross(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int *cross = NULL;
    npy_intp cross_Dims[1] = {-1};
    const int cross_Rank = 1;
    PyArrayObject *capi_cross_as_array = NULL;
    int capi_cross_intent = 0;
    int *a = NULL;
    npy_intp a_Dims[1] = {-1};
    const int a_Rank = 1;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    int *b = NULL;
    npy_intp b_Dims[1] = {-1};
    const int b_Rank = 1;
    PyArrayObject *capi_b_as_array = NULL;
    int capi_b_intent = 0;
    PyObject *b_capi = Py_None;
    static char *capi_kwlist[] = {"a","b",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:g_lightsaber_f.cross",\
        capi_kwlist,&a_capi,&b_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable cross */
    cross_Dims[0]=3;
    capi_cross_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "g_lightsaber_f.g_lightsaber_f.cross: failed to create array from the hidden `cross`";
    capi_cross_as_array = ndarray_from_pyobj(  NPY_INT,1,cross_Dims,cross_Rank,  capi_cross_intent,Py_None,capi_errmess);
    if (capi_cross_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_lightsaber_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cross = (int *)(PyArray_DATA(capi_cross_as_array));

    /* Processing variable a */
    a_Dims[0]=3;
    capi_a_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "g_lightsaber_f.g_lightsaber_f.cross: failed to create array from the 1st argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_INT,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_lightsaber_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (int *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable b */
    b_Dims[0]=3;
    capi_b_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "g_lightsaber_f.g_lightsaber_f.cross: failed to create array from the 2nd argument `b`";
    capi_b_as_array = ndarray_from_pyobj(  NPY_INT,1,b_Dims,b_Rank,  capi_b_intent,b_capi,capi_errmess);
    if (capi_b_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_lightsaber_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        b = (int *)(PyArray_DATA(capi_b_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(cross,a,b);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_cross_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_b_as_array!=b_capi) {
        Py_XDECREF(capi_b_as_array); }
    }  /* if (capi_b_as_array == NULL) ... else of b */
    /* End of cleaning variable b */
    if((PyObject *)capi_a_as_array!=a_capi) {
        Py_XDECREF(capi_a_as_array); }
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
    }  /* if (capi_cross_as_array == NULL) ... else of cross */
    /* End of cleaning variable cross */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of cross ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"gen_lightsaber",-1,{{-1}},0,0,(char *)  F_FUNC_US(gen_lightsaber,GEN_LIGHTSABER),  (f2py_init_func)f2py_rout_g_lightsaber_f_gen_lightsaber,doc_f2py_rout_g_lightsaber_f_gen_lightsaber},
    {"cross",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC(cross,CROSS),  (f2py_init_func)f2py_rout_g_lightsaber_f_cross,doc_f2py_rout_g_lightsaber_f_cross},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "g_lightsaber_f",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_g_lightsaber_f(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = g_lightsaber_f_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module g_lightsaber_f (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.0.1");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'g_lightsaber_f' is auto-generated with f2py (version:2.0.1).\nFunctions:\n"
"    world = gen_lightsaber(pout,point)\n"
"    cross = cross(a,b)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.0.1");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    g_lightsaber_f_error = PyErr_NewException ("g_lightsaber_f.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_g_lightsaber_f_error", g_lightsaber_f_error);
    Py_DECREF(g_lightsaber_f_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }


    {
      extern int F_FUNC(cross,CROSS)(void);
      PyObject* o = PyDict_GetItemString(d,"cross");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(cross,CROSS),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("cross");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"g_lightsaber_f");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
