/* File: g_shooting_star_fmodule.c
 * This file is auto-generated with f2py (version:2.0.1).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Aug 15 20:28:14 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *g_shooting_star_f_error;
static PyObject *g_shooting_star_f_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = g_shooting_star_f_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(gen_shooting_star,GEN_SHOOTING_STAR)(double*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/***************************** gen_shooting_star *****************************/
static char doc_f2py_rout_g_shooting_star_f_gen_shooting_star[] = "\
world = gen_shooting_star(xpos,ypos,zpos)\n\nWrapper for ``gen_shooting_star``.\
\n\nParameters\n----------\n"
"xpos : input float\n"
"ypos : input float\n"
"zpos : input float\n"
"\nReturns\n-------\n"
"world : rank-3 array('d') with bounds (10,10,10)";
/* extern void F_FUNC_US(gen_shooting_star,GEN_SHOOTING_STAR)(double*,double*,double*,double*); */
static PyObject *f2py_rout_g_shooting_star_f_gen_shooting_star(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *world = NULL;
    npy_intp world_Dims[3] = {-1, -1, -1};
    const int world_Rank = 3;
    PyArrayObject *capi_world_as_array = NULL;
    int capi_world_intent = 0;
    double xpos = 0;
    PyObject *xpos_capi = Py_None;
    double ypos = 0;
    PyObject *ypos_capi = Py_None;
    double zpos = 0;
    PyObject *zpos_capi = Py_None;
    static char *capi_kwlist[] = {"xpos","ypos","zpos",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:g_shooting_star_f.gen_shooting_star",\
        capi_kwlist,&xpos_capi,&ypos_capi,&zpos_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable xpos */
        f2py_success = double_from_pyobj(&xpos,xpos_capi,"g_shooting_star_f.gen_shooting_star() 1st argument (xpos) can't be converted to double");
    if (f2py_success) {
    /* Processing variable ypos */
        f2py_success = double_from_pyobj(&ypos,ypos_capi,"g_shooting_star_f.gen_shooting_star() 2nd argument (ypos) can't be converted to double");
    if (f2py_success) {
    /* Processing variable zpos */
        f2py_success = double_from_pyobj(&zpos,zpos_capi,"g_shooting_star_f.gen_shooting_star() 3rd argument (zpos) can't be converted to double");
    if (f2py_success) {
    /* Processing variable world */
    world_Dims[0]=10,world_Dims[1]=10,world_Dims[2]=10;
    capi_world_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "g_shooting_star_f.g_shooting_star_f.gen_shooting_star: failed to create array from the hidden `world`";
    capi_world_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,world_Dims,world_Rank,  capi_world_intent,Py_None,capi_errmess);
    if (capi_world_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = g_shooting_star_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        world = (double *)(PyArray_DATA(capi_world_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(world,&xpos,&ypos,&zpos);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_world_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_world_as_array == NULL) ... else of world */
    /* End of cleaning variable world */
    } /*if (f2py_success) of zpos*/
    /* End of cleaning variable zpos */
    } /*if (f2py_success) of ypos*/
    /* End of cleaning variable ypos */
    } /*if (f2py_success) of xpos*/
    /* End of cleaning variable xpos */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of gen_shooting_star **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"gen_shooting_star",-1,{{-1}},0,0,(char *)  F_FUNC_US(gen_shooting_star,GEN_SHOOTING_STAR),  (f2py_init_func)f2py_rout_g_shooting_star_f_gen_shooting_star,doc_f2py_rout_g_shooting_star_f_gen_shooting_star},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "g_shooting_star_f",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_g_shooting_star_f(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = g_shooting_star_f_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module g_shooting_star_f (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.0.1");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'g_shooting_star_f' is auto-generated with f2py (version:2.0.1).\nFunctions:\n"
"    world = gen_shooting_star(xpos,ypos,zpos)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.0.1");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    g_shooting_star_f_error = PyErr_NewException ("g_shooting_star_f.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_g_shooting_star_f_error", g_shooting_star_f_error);
    Py_DECREF(g_shooting_star_f_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"g_shooting_star_f");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
