C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.0.1)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapcross (crossf2pywrap, a, b)
      external cross
      integer a(3)
      integer b(3)
      integer crossf2pywrap(3)
      integer (3) cross
      crossf2pywrap = cross(a, b)
      end

